language: java

jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  except:
    - gh-pages

cache:
  directories:
    - $HOME/.m2

env: MAVEN_OPTS="-Xmx2G -XX:MaxPermSize=256m"
install: /bin/true
script: mvn clean install